# Generated by Django 4.2.6 on 2023-11-13 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('mask_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('mask_location', models.URLField()),
                ('mask_prompt', models.CharField(max_length=200)),
                ('mask_seed', models.IntegerField(default=0)),
                ('mask_creation_date', models.DateTimeField(verbose_name='date published')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('src_video_location', models.URLField()),
                ('video_location', models.URLField()),
                ('video_creation_date', models.DateTimeField(verbose_name='date published')),
                ('mask_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facemasq.mask')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('src_photo_location', models.URLField()),
                ('photo_location', models.URLField()),
                ('photo_creation_date', models.DateTimeField(verbose_name='date published')),
                ('mask_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facemasq.mask')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
